# Generated by Django 6.1 on 2026-08-16 19:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Bambu Lab', max_length=100)),
                ('type', models.CharField(default='PLA+', help_text='e.g. PLA+, PETG, ABS, TPU 95A, PLA-CF, Resin', max_length=50)),
                ('color_name', models.CharField(max_length=100)),
                ('color_hex', models.CharField(default='#ff5500', max_length=10)),
                ('spool_price', models.DecimalField(decimal_places=2, default=Decimal('2400.00'), help_text='Total spool purchase price in BDT (৳)', max_digits=10)),
                ('full_weight', models.IntegerField(default=1000, help_text='Full spool weight in grams')),
                ('current_stock', models.IntegerField(default=1000, help_text='Remaining grams in stock')),
                ('location', models.CharField(blank=True, help_text='e.g. AMS Slot 1, Rack A-01', max_length=100, null=True)),
                ('nozzle_temp', models.CharField(blank=True, default='210°C - 230°C', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Filament Spool',
                'verbose_name_plural': 'Filament Spools',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudioSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_rate_per_gram', models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Amount kept for Company Account per gram in BDT', max_digits=5)),
                ('studio_name', models.CharField(default='StudioMistri', max_length=150)),
                ('studio_tagline', models.CharField(default='THINK • DESIGN • MAKE', max_length=200)),
                ('studio_phone', models.CharField(default='+880 1700-000000', max_length=50)),
                ('studio_email', models.EmailField(default='contact@studiomistri.com', max_length=254)),
                ('studio_bkash', models.CharField(default='01700-000000 (bKash/Nagad)', max_length=100)),
                ('studio_address', models.CharField(default='StudioMistri Fabrication Hub, Dhaka, Bangladesh', max_length=255)),
                ('price_presets', models.JSONField(blank=True, default=dict, help_text='Default rate per gram by material type')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Studio Setting',
                'verbose_name_plural': 'Studio Settings',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('model_name', models.CharField(max_length=255)),
                ('model_size', models.CharField(blank=True, default='120 x 85 x 150 mm', max_length=100)),
                ('filament_name_snapshot', models.CharField(blank=True, max_length=100)),
                ('filament_type_snapshot', models.CharField(blank=True, max_length=50)),
                ('filament_color_hex_snapshot', models.CharField(blank=True, default='#ff5500', max_length=10)),
                ('filament_brand_snapshot', models.CharField(blank=True, max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Model net weight in grams', max_digits=10)),
                ('price_per_gram', models.DecimalField(decimal_places=2, default=Decimal('7.00'), help_text='Selling rate per gram in BDT', max_digits=10)),
                ('extra_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Post-processing, sanding, inserts, etc.', max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Total order amount payable in BDT', max_digits=10, null=True)),
                ('company_share', models.DecimalField(blank=True, decimal_places=2, help_text='3 Tk/g Company Fund allocation', max_digits=10, null=True)),
                ('salary_share', models.DecimalField(blank=True, decimal_places=2, help_text='Remainder to Maker Salary Account', max_digits=10, null=True)),
                ('material_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Raw material spool cost in BDT', max_digits=10)),
                ('status', models.CharField(choices=[('Quotation', 'Quotation / Draft'), ('Slicing', 'Slicing & Gcode'), ('Printing', 'Printing in Progress 🖨️'), ('Post-Processing', 'Post-Processing'), ('Delivered', 'Delivered'), ('Paid', 'Paid & Closed ✅')], default='Printing', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='studio.filament')),
            ],
            options={
                'verbose_name': '3D Print Order',
                'verbose_name_plural': '3D Print Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
